Repository MetOffice/opsinputs, pull requests merged in 2023-10, with the labels that each got.

#184 add clang container to CI workflow
  .github/workflows/ci.yml
  ci/build-and-test
Labels: enhancement, ready to merge, INFRA

#185 Write H(x) into CX for sonde data in JADA
  src/opsinputs/CxWriterParameters.h
  src/opsinputs/opsinputs_cxwriter_mod.F90
  src/opsinputs/opsinputs_fill_mod.F90
  test/testinput/002_UpperAirCxField_rh_Sonde.yaml
Labels: ready to merge

#187 Fix CI housekeep
  .github/workflows/ci.yml
  ci/CMakeLists.txt
  ci/build-and-test
Labels: bug, ready to merge
