Repository MetOffice/opsinputs, pull requests merged in 2024-05, with the labels that each got.

#202 Remove literal kinds
  src/opsinputs/opsinputs_fill_mod.F90
  src/opsinputs/opsinputs_varobswriter_mod.F90
Labels: ready to merge

#203 AOCC support
  deps/CMakeLists.txt
  src/opsinputs/CMakeLists.txt
Labels: ready to merge

#200 Changes needed for the VarBc code sprint at JCSDA
  src/opsinputs/opsinputs_varobswriter_mod.F90
  test/generate_unittest_netcdfs.py
  test/testinput/080_VarField_biaspredictors.nc4
Labels: coordinated merge, ready to merge

#206 Account for integer `MetaData/stationIdentification`
  src/opsinputs/VarObsWriterParameters.h
  src/opsinputs/opsinputs_fill_mod.F90
  src/opsinputs/opsinputs_varobswriter_mod.F90
  test/CMakeLists.txt
  test/generate_unittest_netcdfs.py
  test/testinput/001_VarField_pstar_stationID_integer.nc4
  test/testinput/001_VarField_pstar_stationID_integer.yaml
Labels: ready to merge

#207 Fixes the failures associated with oops ObsVariables introduction
  src/opsinputs/CxWriter.cc
  src/opsinputs/CxWriter.h
  src/opsinputs/CxWriter.interface.F90
  src/opsinputs/CxWriter.interface.h
  src/opsinputs/VarObsWriter.cc
  src/opsinputs/VarObsWriter.h
  src/opsinputs/VarObsWriter.interface.F90
  src/opsinputs/VarObsWriter.interface.h
  src/opsinputs/opsinputs_cxwriter_mod.F90
  src/opsinputs/opsinputs_fill_mod.F90
  src/opsinputs/opsinputs_obsdatavector_f.cc
  src/opsinputs/opsinputs_obsdatavector_f.h
  src/opsinputs/opsinputs_varobswriter_mod.F90
  test/opsinputs/CxChecker.h
  test/opsinputs/ResetFlagsToPass.cc
  test/opsinputs/ResetFlagsToPass.h
  test/opsinputs/VarObsChecker.cc
  test/opsinputs/VarObsChecker.h
Labels: bug, ready to merge

#208 Update global surface CX namelist
  etc/global/cx/Surface.nl
Labels: ready to merge
