Repository MetOffice/opsinputs, pull requests merged in 2024-07, with the labels that each got.

#214 Add namelist and ctest files/yamls for SEVIRI UKV
  etc/ukv/cx/SEVIRIASR.nl
  etc/ukv/cx/SEVIRIClr.nl
  etc/ukv/varobs/SEVIRIASR.nl
  etc/ukv/varobs/SEVIRIClr.nl
  test/CMakeLists.txt
  test/generate_unittest_netcdfs.py
  test/testinput/cx_ukvnamelist_seviriasr.nc4
  test/testinput/cx_ukvnamelist_seviriclr.nc4
  test/testinput/cxwriter_ukvnamelist_seviriasr.yaml
  test/testinput/cxwriter_ukvnamelist_seviriclr.yaml
  test/testinput/varobs_ukvnamelist_seviriasr.nc4
  test/testinput/varobs_ukvnamelist_seviriclr.nc4
  test/testinput/varobswriter_ukvnamelist_seviriasr.yaml
  test/testinput/varobswriter_ukvnamelist_seviriclr.yaml
Labels: ready to merge

#216 Adding windspeed varobs test and oceanwinds var_cx test
  Varfields.md
  etc/global/cx/Oceanwinds.nl
  src/opsinputs/opsinputs_varobswriter_mod.F90
  test/CMakeLists.txt
  test/generate_unittest_netcdfs.py
  test/testinput/008_VarField_WindSpeed.nc4
  test/testinput/008_VarField_WindSpeed.yaml
  test/testinput/cx_globalnamelist_oceanwinds.nc4
  test/testinput/cxwriter_globalnamelist_oceanwinds.yaml
Labels: enhancement, ready to merge

#218 General Mode in post filters now as per yaml
  src/opsinputs/opsinputs_cxwriter_mod.F90
  src/opsinputs/opsinputs_varobswriter_mod.F90
Labels: ready to merge

#219 Add build-group strategy
  .github/CODEOWNERS
  .github/workflows/ci.yml
  .github/workflows/manual.yml
  ci/CMakeLists.txt
  ci/build-and-test
  ci/check-build-group.sh
Labels: ready to merge, INFRA
